name: lexi_learn
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  dio: ^5.3.3
  provider: ^6.0.5
  go_router: ^12.0.0
  url_launcher: ^6.1.14
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
  
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Black.ttf
          weight: 900

# w100 Thin, the least thick
# w200 Extra-light
# w300 Light
# w400 Normal / regular / plain
# w500 Medium
# w600 Semi-bold
# w700 Bold
# w800 Extra-bold
# w900 Black, the most thick